# Generated by Django 4.2 on 2023-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='company_name',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(related_name='organizers', to='events.event'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
